export const IPC_CHANNELS = {
  appGetBootstrapStatus: 'app:getBootstrapStatus',
  appCopyText: 'app:copyText',
  vaultSetup: 'vault:setup',
  vaultUnlock: 'vault:unlock',
  vaultLock: 'vault:lock',
  vaultGetStatus: 'vault:getStatus',
  vaultSetTrustedDeviceUnlock: 'vault:setTrustedDeviceUnlock',
  profilesList: 'profiles:list',
  profilesCreate: 'profiles:create',
  profilesUpdate: 'profiles:update',
  profilesDelete: 'profiles:delete',
  entriesListByProfile: 'entries:listByProfile',
  entriesCreate: 'entries:create',
  entriesUpdate: 'entries:update',
  entriesDelete: 'entries:delete',
  entriesCopyPassword: 'entries:copyPassword',
} as const;
